apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace : test
spec:
  hard:
    pods: "20" 
    requests.cpu: "1" 
    requests.memory: 2Gi 
    requests.ephemeral-storage: 5Gi 
    limits.cpu: "4" 
    limits.memory: 8Gi 
    limits.ephemeral-storage: 10Gi