apiVersion: v1
kind: Pod
metadata:
  name: nvidia-smi
  namespace : test
spec:
  restartPolicy: OnFailure
  containers:
  - name: main
    image: nvidia/cuda:12.3.2-runtime-centos7
    args:
    - "nvidia-smi"
    volumeMounts:
    - name: ephemeral
      mountPath: "/tmp"
    resources:
      limits:
        nvidia.com/gpu: 1
        memory: "1000Mi"
        cpu: "1"
        ephemeral-storage: "4Gi"
      requests:
        nvidia.com/gpu: 1
        memory: "500Mi"
        cpu: "1"
        ephemeral-storage: "2Gi"
  volumes:
    - name: ephemeral
      emptyDir:
        sizeLimit: 500Mi        
  tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule     