apiVersion: v1
kind: Pod
metadata:
  name: pytorch-pytest
  namespace : test  
spec:
  restartPolicy: OnFailure
  containers:
  - name: main
    image: nvcr.io/nvidia/pytorch:24.02-py3
    command: 
      - /bin/bash
      - -c    
      - |
        python -c "import torch; gpus = torch.cuda.device_count(); print(f'Available GPUs: {gpus}'); [print(f'GPU {gpu}: {torch.cuda.get_device_name(gpu)}') for gpu in range(gpus)]"
    resources:
      limits:
        nvidia.com/gpu: 1