apiVersion: v1
kind: Pod
metadata:
  name: pytorch
  namespace : test  
spec:
  restartPolicy: OnFailure
  containers:
  - name: main
    image: nvcr.io/nvidia/pytorch:24.02-py3
    command: ['sleep', '360000']
    resources:
      limits:
        nvidia.com/gpu: 1